name: Build, Test, and Deliver

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 10  # Timeout for the job

    env:
      Solution_Name: PdfLocker.sln  # Solution name
      Test_Project_Dir: UnitTest
      Test_Project_Path: UnitTest\UnitTest.csproj  # Path to the unit test project

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch the full Git history

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore $env:Solution_Name

    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=Release  # Specify "Release"

    - name: Build the unit test project
      run: msbuild $env:Test_Project_Path /p:Configuration=Release  # Specify "Release"

    - name: Execute unit tests
      run: dotnet vstest $env:Test_Project_Dir\bin\Release\UnitTest.dll

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: Build-Output  # A generic name for the artifact
        path: PdfLocker\bin\Release

  delivery:
    needs: build  # Run this job only after the "build" job is successful
    runs-on: windows-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: Build-Output
        path: build_output  # Path where the artifact will be downloaded

    - name: List downloaded artifacts
      run: dir build_output  # Verify the downloaded files

    - name: Prepare portable build
      run: |
        mkdir out
        # Copy .exe, .dll, .config, and .pdb files to the portable directory
        xcopy build_output\*.exe out\Portable /s /i
        xcopy build_output\*.dll out\Portable /s /i
        xcopy build_output\*.config out\Portable /s /i  # Include .config if needed
        xcopy build_output\*.pdb out\Portable /s /i  # Include .pdb if needed

    - name: Upload portable build as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Portable-Build
        path: out\Portable

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Use your personal access token
        tag: v1.0.${{ github.run_number }}
        releaseName: "Portable Release v1.0.${{ github.run_number }}"
        files: out\Portable\*
