name: Delivery

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  deliver:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: Build-Output
        path: build

    - name: Prepare portable build
      run: |
        mkdir out
        xcopy build\ out\Portable /s /i

    - name: Upload portable build as artifact
      uses: actions/upload-artifact@v3
      with:
        name: Portable-Build
        path: out\Portable

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: v1.0.${{ github.run_number }}
        releaseName: "Portable Release v1.0.${{ github.run_number }}"
        files: out\Portable\*
