name: Delivery

on:
  workflow_run:
    workflows: ["Build And Test"]  # Le nom exact du workflow que tu veux suivre
    types:
      - completed  # S'exécute lorsque le workflow Build and Test est terminé

jobs:
  deliver:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Seulement si le workflow précédent a réussi
    runs-on: windows-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: Build-Output-${{ github.event.workflow_run.id }}  # Utilisation du run_id du workflow Build and Test
        path: build_output  # Le dossier où tu veux télécharger l'artefact

    - name: List downloaded artifacts
      run: dir build_output  # Afficher le contenu du dossier build_output pour vérifier les fichiers téléchargés
    
    - name: Prepare portable build
      run: |
        mkdir out
        xcopy build_output\* out\Portable /s /i

    - name: Upload portable build as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Portable-Build
        path: out\Portable

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: v1.0.${{ github.run_number }}
        releaseName: "Portable Release v1.0.${{ github.run_number }}"
        files: out\Portable\*
